import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

export default function Home() {
    return (
        <>
            <Head>
                <title>Fresko Kiosk</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Link href="/order">
                    <Image
                        src="/home.svg"
                        width={500}
                        height={800}
                        alt="home"
                    />
                </Link>
            </main>
        </>
    );
}
